package main

var staticFiles map[string]string

func init() {
	staticFiles = map[string]string{
		".eleventy.js": `// Generated by wp-to-11ty
const { DateTime } = require("luxon");

module.exports = function(eleventy) {
  eleventy.addFilter("strftime", function(dateObj, format) {
    return DateTime.fromJSDate(dateObj, {zone: 'utc'}).toFormat(format);
  });

  return {};
};
`,
		"package.json": `{
  "name": "blog",
  "version": "1.0.0",
  "description": "wp-to-11ty export",
  "main": "",
  "dependencies": {
    "luxon": "^1.21.2"
  },
  "devDependencies": {},
  "scripts": {
    "serve": "eleventy --serve",
    "build": "eleventy"
  },
  "author": ""
}
`,
		"_includes/layout.njk": `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/mini.css/3.0.1/mini-default.min.css">
    <title>{{ title }} | {{ blog.title }}</title>
  </head>
  <body>
    <header>
      <a href="/" class="button logo"><span class="icon-home"></span></a>
      {%- for page in collections.page -%}
      <a href="{{ page.url }}" class="button">{{ page.data.title }}</a>
      {%- endfor -%}
    </header>
    <div class="container">
      <div class="row">
        <div class="col-sm-9">
          <h1>{{ title }}</h1>
          {{ content | safe }}
        </div>
        <div class="col-sm-3">
          <p>{{ blog.description }}</p>
        </div>
      </div>
    </div>
  </body>
</html>
`,
		"index.njk": `---
title: Blog Posts
layout: layout.njk
pagination:
  data: collections.post
  size: 10
  reverse: true
---

{%- for post in pagination.items -%}
<div>
  <h2><a href="{{ post.url }}">{{ post.data.title }}</a></h2>
  {{ post.date | strftime("LLL d, y") }}
  {{ post.data.summary }}
</div>
{%- endfor -%}
`,
	}
}
